imrg_web/Controllers/UserRolesController.cs
using imrg_web.BLL.Roles;
using imrg_web.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace imrg_web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserRolesController : Controller
    {

        private imrgEntities db = new imrgEntities();
        // GET: UserRoles
        public ActionResult Index()
        {
            var users = db.AspNetUsers.ToList();
            var roles = db.AspNetRoles.ToList();
            return View(users);
        }

        public ActionResult AssignUserRoles(string id)
        {
            var user = db.AspNetUsers.Find(id);
            if(user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            db.Entry(user).Collection(x => x.AspNetRoles).Load();
            var assignedRoles = user.AspNetRoles.Select(x => x.Id);
            var roles = db.AspNetRoles.Where(x => !assignedRoles.Contains(x.Id)).ToList();

            var assignUserRolesModel = AssignUserRolesViewModel.Create(user, roles);

            return View(assignUserRolesModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AssignUserRoles([Bind(Include= "UserId, RoleId")]AssignUserRolesViewModel model)
        {
            var role = db.AspNetRoles.Find(model.RoleId);
            if(role == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = db.AspNetUsers.Find(model.UserId);
            if(user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if(user.AspNetRoles.FirstOrDefault(x=> x.Id == role.Id) == null)
            {
                user.AspNetRoles.Add(role);
                db.Entry(role).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return RedirectToAction("AssignUserRoles", new { id = user.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveUserRoles([Bind(Include = "UserId, RoleId")]AssignUserRolesViewModel model)
        {
            var role = db.AspNetRoles.Find(model.RoleId);
            if (role == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = db.AspNetUsers.Find(model.UserId);
            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (user.AspNetRoles.FirstOrDefault(x => x.Id == role.Id) != null)
            {
                user.AspNetRoles.Remove(role);
                db.Entry(role).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return RedirectToAction("AssignUserRoles", new { id = user.Id });
        }



    }
}

imrg_web/Views/UserRoles/AssignUserRoles.cshtml
@model imrg_web.BLL.Roles.AssignUserRolesViewModel

@{
    ViewBag.Title = "Assign Roles";
}

<h2>Assign Roles</h2>




<div class="form-horizontal">
    <h4>Role</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.User.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.User.Email)
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Current Roles", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @foreach (var role in Model.User.AspNetRoles)
            {
                using (Html.BeginForm("RemoveUserRoles", "UserRoles"))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.UserId)
                    <input type="hidden" name="RoleId" value="@role.Id" />
                    <dl class="dl-horizontal">
                        <dt>
                            <p>@role.Name </p>
                        </dt>
                        <dd>
                            <input type="submit" value="Remove" class="btn btn-default" />
                        </dd>
                    </dl>
                }
            }
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.UserId)
        <div class="form-group">
            @Html.Label("Roles", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.RoleId, new SelectList(Model.AvailableRoles, "Id", "Name"), "  -----Select Role-----  ", htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    }

</div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

imrg_web/Views/UserRoles/Index.cshtml
@model IEnumerable<imrg_web.Models.AspNetUser>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Manage Roles", "AssignUserRoles", new { id=item.Id  }) 
            </td>
        </tr>
    }

</table>